### ISSUE TITLE
question for modifying model

### ISSUE THREAD

**Issue by Lim-Sung-Jun** [tira-io/ir-experiment-platform#7] opened 2023-09-20 05:30 UTC
hello

how can i use the pipeline with modified colbert?

where can i find colbert code? do i have to git clone the colbert code into directory?

i want to check the performance with modified colbert

thank you!

**Comment by mam10eks** [comment] 2023-09-20 12:28
Thanks for creating this issue!
This seems to be a duplicate of https://github.com/tira-io/ir-experiment-platform/issues/6, or?
So I close it, in case I did this wrongly, please reopen the issue.

Best regards,

Maik

**Closed as completed by mam10eks** 2023-09-20 12:28 UTC
